name: Manual Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version (example: 6.20.0)'
        required: true
        type: string
      base32_version:
        description: 'Base32 version'
        required: true
        type: string
      is_lts:
        description: 'LTS release'
        required: true
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GIT_TERMINAL_PROMPT: 0

    steps:
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/

      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate
        uses: actions/github-script@v6
        env: 
          release_version: ${{ github.event.inputs.release_version }}
          base32_version: ${{ github.event.inputs.base32_version }}
        with:
          script: |
            const { release_version, base32_version } = process.env
            const validReleaseVersion = /^\d{1,2}\.\d{1,2}\.\d{1,2}$/.test(release_version)
            const validBase32 = /^[A-Z]{2}$/.test(base32_version)
            
            if(!validReleaseVersion){
              core.setFailed("Invalid release version, use format: major.minor.patch (6.20.0)");
            }
            if(!validBase32){
              core.setFailed("Invalid base32 version, use two capital letters. Like: AA")
            }

      - name: Create and populate PoC file
        env: 
          release_version: ${{ github.event.inputs.release_version }}
          base32_version: ${{ github.event.inputs.base32_version }}
        run: |
          touch input-poc.txt
          echo release_version="$AWS_HOST" >> input-poc.txt
          echo base32_version="$AWS_PORT" >> input-poc.txt
          
      - name: Create release branch
        env:
          release_version: ${{ github.event.inputs.release_version }}
        run: |
          # git remote -v
          git fetch origin
          git checkout -b release/$release_version
          # git status
          git add input-poc.txt

          git config --global user.email "dannyvanderjagt@gmail.com"
          git config --global user.name "Danny van der Jagt (CI)"

          git commit -m "Add poc file"
          git push release/$release_version
          # git fetch
          # git remote update
          # git fetch
          # git status

        



      
    # TODO: checkout branch and pull code

    # TODO: Print inputs into file

    # TODO: Create a release branch

    # TODO: Push commit with the updated file


      # - name: 
      # - name: Print base32_version
      #   run: echo base32_version ${{ github.events.inputs.base32_version }}
      # - name: Print branch
      #   run: echo branch ${{ github.events.inputs.branch }}
      # - name: Print is_lts
      #   run: echo is_lts ${{ github.events.inputs.is_lts }}