name: Manual Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version (example: 6.20.0)'
        required: true
        type: string
      base32_version:
        description: 'Base32 version'
        required: true
        type: string
      is_lts:
        description: 'LTS release'
        required: true
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GIT_TERMINAL_PROMPT: 0
      RELEASE_VERSION: ${{ github.event.inputs.release_version }}
      BASE32_VERSION: ${{ github.event.inputs.base32_version }}

    steps:
      - uses: actions/checkout@v3
    
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global --add url."https://github.com/".insteadOf
          ssh://git@github.com/

      - name: Validate
        uses: actions/github-script@v6
        with:
          script: |
            const { RELEASE_VERSION, BASE32_VERSION } = process.env
            const validReleaseVersion = /^\d{1,2}\.\d{1,2}\.\d{1,2}$/.test(RELEASE_VERSION)
            const validBase32 = /^[A-Z]{2}$/.test(BASE32_VERSION)
            
            if(!validReleaseVersion){
              core.setFailed("Invalid release version, use format: major.minor.patch (6.20.0)");
            }
            if(!validBase32){
              core.setFailed("Invalid base32 version, use two capital letters. Like: AA")
            }

      - name: Create and populate PoC file
        run: |
          touch input-poc.txt
          echo release_version="$RELEASE_VERSION" >> input-poc.txt
          echo base32_version="$BASE32_VERSION" >> input-poc.txt
          
      - name: Create release branch
        env:
          release_version: ${{ github.event.inputs.release_version }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

          git fetch origin
          git checkout -b release/$release_version
          git add input-poc.txt

          git config --global user.email "dannyvanderjagt@gmail.com"
          git config --global user.name "Danny van der Jagt (CI)"

          git commit -m "Add poc file"
          git push origin release/$release_version

      
    # TODO: checkout branch and pull code

    # TODO: Print inputs into file

    # TODO: Create a release branch

    # TODO: Push commit with the updated file


      # - name: 
      # - name: Print base32_version
      #   run: echo base32_version ${{ github.events.inputs.base32_version }}
      # - name: Print branch
      #   run: echo branch ${{ github.events.inputs.branch }}
      # - name: Print is_lts
      #   run: echo is_lts ${{ github.events.inputs.is_lts }}